server:
  port: 8080
spring:
  application:
    name: learning-platform
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learningplatform?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1314520xx
  jpa:
    database: mysql
    show-sql: true
punch_in_number: 3
multipart.maxFileSize: 200
multipart.maxRequestSize: 200
read_time: 3
init_password: 00000000
